<template>
  <div class="wizard-project">
    <div class="layout__header">
      <h1 class="title">
        <font-awesome-icon icon="sync-alt" /> Updater
      </h1>

      <h2 class="subtitle">
        {{ checkpoints.title }}
      </h2>
    </div>

    <div class="project__content">
      <div class="project__update">
        <div v-if="!requirements.power.checkpoints" class="notification notification--warning">
          This component is required to continue using {{ $dream.name }}.
        </div>

        <div v-else class="notification">
          Installed version: <strong>{{ checkpoints.currentVersion }}</strong>
        </div>

        <ProjectUpdate project="checkpoints" />

        <div class="text-center mt-6">
          <button class="button" @click="$dream.openPowerFolder()">
            <span class="icon"><font-awesome-icon icon="folder-open" /></span>
            <span>DreamPower</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { isNil } from 'lodash'
import { dreamtrack } from '~/modules/services'
import { requirements } from '~/modules/system'

const { dialog } = $provider.api
const { existsSync } = $provider.fs

export default {
  layout: 'wizard',

  middleware({ redirect }) {
    if (requirements.power.checkpoints) {
      redirect('/wizard/telemetry')
    }
  },

  data: () => ({
    requirements,
  }),

  computed: {
    checkpoints() {
      return dreamtrack.get('projects.checkpoints.about', {
        title: 'Checkpoints',
        description: 'Data models generated by the AI.',
      })
    },
  },

  methods: {
    showOpenDialog(path) {
      const dir = dialog.showOpenDialogSync({
        defaultPath: path,
        properties: ['openDirectory'],
      })

      if (isNil(dir)) {
        return path
      }

      if (!existsSync(dir[0])) {
        // ???
        return path
      }

      return dir[0]
    },

    changePower() {
      const dir = this.showOpenDialog(this.$settings.folders.cli)
      this.$settings.folders.cli = dir
    },
  },
}
</script>

<style lang="scss" scoped>
</style>
